# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "siderolabs/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.5.1"

pre_release = false

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1beta1"
        description = """\
CABPT supports CAPI version 1.x (v1beta1).
"""

    [notes.hostname]
        title = "Hostnames in the Talos Machine Configuration"
        description = """\
Hostname in the generated Talos machine configuration can be set to the corresponding `Machine` name:

```yaml
spec:
  hostname:
    source: MachineName
```
"""
